mysite/urls.py
from django.conf.urls import include, url
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from django.contrib import admin
from django.urls import re_path
from django.conf import settings
from django.views.static import serve

API_TITLE = 'SLQMS API'
API_DESCRIPTION = 'A Web API for requesting Student Learning Quality Monitoring System project result.'
schema_view = get_schema_view(title=API_TITLE)

urlpatterns = [
    url(r'^', include('xadmin.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^schema/$', schema_view),
    url(r'^docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    url('admin/', admin.site.urls),
    re_path(r'media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

xadmin/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter
from django.urls import path

from xadmin import views

app_name = 'xadmin'

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'teachers', views.TeacherViewSet)
router.register(r'classes', views.ClassViewSet)
router.register(r'students', views.StudentViewSet)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    path('login/', views.LoginView.as_view(), name='login'),
    path('val/', views.val, name='val'),
    path('teachclass/<int:tid>/', views.TeachClassView, name='teachclass'),
    path('teachclassapi/<int:tid>/', views.TeachClassAPI, name='teachclassapi'),
    path('teachclass/<int:tid>/class/<int:cid>/table/', views.TeachStudentTableView, name='teachstudenttable'),
    path('teachclass/<int:tid>/class/<int:cid>/chart/', views.TeachStudentChartView, name='teachstudentchart'),
    path('student/<int:sid>/', views.StudentView, name='student'),
    path('studentapi/<int:sid>/', views.StudentAPI, name='studentapi'),
    path('studentsapi/<int:cid>/', views.StudentsAPI, name='studentsapi'),
]

xadmin/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    pwd = models.CharField(max_length=255)
    class Meta:
        db_table = 'teacher'
        ordering = ['id']
        verbose_name = 'TeacherTable'
        verbose_name_plural = verbose_name

class Class(models.Model):
    name = models.CharField(max_length=255)
    tid = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    class Meta:
        db_table = 'class'
        ordering = ['id']
        verbose_name = 'ClassTable'
        verbose_name_plural = verbose_name

class Student(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    pwd = models.CharField(max_length=255)
    video_watching_counts = models.FloatField()
    video_watching_seconds = models.FloatField()
    course_discuss_related = models.FloatField()
    course_discuss_unrelated = models.FloatField()
    discuss_topic_numbers = models.FloatField()
    discussion_comment_and_reply_numbers = models.FloatField()
    spoc_score = models.FloatField()
    test_mean = models.FloatField()
    cid = models.ForeignKey(Class, on_delete=models.CASCADE)
    level = models.CharField(max_length=10, null=True, blank=True)
    advice = models.CharField(max_length=255, null=True, blank=True)
    class Meta:
        db_table = 'student'
        ordering = ['id']
        verbose_name = 'StudentTable'
        verbose_name_plural = verbose_name

xadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.conf import settings

from xadmin.models import Teacher, Class, Student
from xadmin.serializers import TeacherSerializer, ClassSerializer, StudentSerializer

from rest_framework import viewsets
from rest_framework.response import Response

import sklearn
import pandas as pd
import seaborn as sb
import numpy as np
import joblib
import json

# Create your views here.

class LoginView(generic.ListView):
    template_name = 'xadmin/login.html'
    model = Student

def val(request):
    id = request.POST['username']
    pwd = request.POST['password']
    role = request.POST['role']
    if role == 'student':
        try:
            s = Student.objects.get(id=id)
            if pwd == s.pwd:
                return redirect('/student/{}/'.format(s.id))
                # return HttpResponse("登录成功!")
            else:
                return HttpResponse("密码不正确,登录失败!")
        except (KeyError, Student.DoesNotExist):
            return HttpResponse("用户不存在, 请重新输入信息后登录!")
    else:
        try:
            t = Teacher.objects.get(id=id)
            if pwd == t.pwd:
                return redirect('/teachclass/{}/'.format(t.id))
                # return HttpResponse("登录成功!")
            else:
                return HttpResponse("密码不正确,登录失败!")
        except (KeyError, Teacher.DoesNotExist):
            return HttpResponse("用户不存在, 请重新输入信息后登录!")

def TeachClassView(request, tid):
    t = get_object_or_404(Teacher, pk=tid)
    t.info = '{}-{}'.format(t.id, t.name)
    return render(request, 'xadmin/teachclass.html', {'teacher': t})

def TeachClassAPI(request, tid):
    classes = Class.objects.filter(tid=tid)
    serializer =  ClassSerializer(classes, many=True)
    data = {
        "code": 0,
        "msg": "",
        "count": len(serializer.data),
        "data": serializer.data,
    }
    return JsonResponse(data, safe=True)

def TeachStudentTableView(request, tid, cid):
    t = get_object_or_404(Teacher, pk=tid)
    t.info = '{}-{}'.format(t.id, t.name)
    c = get_object_or_404(Class, pk=cid)
    return render(request, 'xadmin/teachstudenttable.html', {'teacher': t, 'class': c})
def TeachStudentChartView(request, tid, cid):
    t = get_object_or_404(Teacher, pk=tid)
    t.info = '{}-{}'.format(t.id, t.name)
    c = get_object_or_404(Class, pk=cid)
    return render(request, 'xadmin/teachstudentchart.html', {'teacher': t, 'class': c})

def StudentView(request, sid):
    students = Student.objects.filter(id=sid)
    students = inference(students)
    s = students[0]
    s.info = '{}-{}-{}'.format(s.id, s.name, s.cid.name)
    return render(request, 'xadmin/student.html', {'student': s})

def inference(query_sets):
    print(type(query_sets))
    models_root = settings.STATIC_ROOT / 'models'
    with (models_root / 'cfgs.json').open() as f:
        cfgs = json.load(f)
        if cfgs['mode'] == 'LR':
            model = joblib.load(models_root / 'lr.pkl')
        elif cfgs['mode'] == 'SVM':
            model = joblib.load(models_root / 'svm.pkl')
        else:  # MLP
            model = joblib.load(models_root / 'mlp.pkl')
        
        dataframe = pd.DataFrame(list(query_sets.values())).iloc[:, 3:11]
    levels = model.predict(dataframe)
    # print('levels', levels)
    id2level = {
        '0': 'A',
        '1': 'B',
        '2': 'C'
    }
    id2advice = {
        '0': '学习质量高，请继续以同样方法和步幅坚持学习，祝你最后期末取得佳绩',
        '1': '学习质量一般，请尝试根据自身不足多加复习，查漏补缺，及时调整学习步幅和方法有助于提高学习质量',
        '2': '学习质量较差，若继续以过往步幅和方法进行学习，将很有可能导致期末分数不及格，请迅速做出更改，努力学习',
    }
    for i, s in enumerate(query_sets):
        s.level = id2level[str(levels[i])]
        s.advice = id2advice[str(levels[i])]
    return query_sets


def StudentAPI(reqeust, sid):
    students = Student.objects.filter(id=sid)
    students = inference(students)
    serializer = StudentSerializer(students, many=True)
    data = {
        "code": 0,
        "msg": "",
        "count": len(serializer.data),
        "data": serializer.data,
    }
    return JsonResponse(data, safe=True)
def StudentsAPI(reqeust, cid):
    students = Student.objects.filter(cid=cid)
    students = inference(students)
    serializer = StudentSerializer(students, many=True)
    cnts = {
        'A': 0,
        'B': 0,
        'C': 0,
    }
    for s in students:
        cnts[s.level] += 1
    # stat = {
    #     'categories': ['优秀', '良好', '不合格'],
    #     'values': [cnts['A'] * 100 // len(students),\
    #         cnts['B'] * 100 // len(students), cnts['C'] * 100 // len(students)]
    # }
    stat = [
        {'value': cnts['A'] * 100 // len(students), 'name': '优秀'},
        {'value': cnts['B'] * 100 // len(students), 'name': '良好'},
        {'value': cnts['C'] * 100 // len(students), 'name': '不合格'},
    ]
    data = {
        "code": 0,
        "msg": "",
        "count": len(serializer.data),
        "statistics": stat,
        "data": serializer.data,
    }
    return JsonResponse(data, safe=True)

class StudentViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    """
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
class TeacherViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    """
    queryset = Teacher.objects.all()
    serializer_class = TeacherSerializer
class ClassViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    """
    queryset = Class.objects.all()
    serializer_class = ClassSerializer

xadmin/templates/xadmin/login.html
<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title>登录 | 学生学习质量监测系统</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
	<link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/layui/layui.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}" charset="utf-8"></script>
</head>
<body class="login-bg">
    
    <div class="login layui-anim layui-anim-up">
        <div class="message">学生学习质量检测系统</div>
        <div id="darkbannerwrap"></div>
        
        <form  class="layui-form" action="{% url 'xadmin:val' %}" method="post">
        {% csrf_token %}
          <input name="username" placeholder="用户名"  type="text" lay-verify="required" class="layui-input" >
          <hr class="hr15">
          <input name="password" lay-verify="required" placeholder="密码"  type="password" class="layui-input">
          <hr class="hr15">
          <div class="layui-input-inline">
		      	<input type="radio" name="role" value="student" title="学生">
	      		<input type="radio" name="role" value="teacher" title="教师" checked>
		      </div>
          <input value="登录" style="width:100%;" type="submit">
          <hr class="hr20" >
        </form>
    </div>

    <script>
        $(function  () {
            layui.use('form', function(){
              var form = layui.form;
            });
        })
    </script>
    <!-- 底部结束 -->
</body>
</html>

xadmin/templates/xadmin/student.html
<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title>学生学习质量监测系统</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
	<link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/layui/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
</head>
<body>
    <!-- 以下隐藏input是为了实现jsp全局变量引入到js中便于layui url传值 -->
	<input type="hidden" id="sid" value="{{student.id}}">
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo">
            <a href="{% url 'xadmin:student' student.id %}">学生学习质量监测系统 </a>
        </div>
        <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    {{student.info}}
                </a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd>
                        <a onclick="x_admin_show('个人信息','http://www.baidu.com')">个人信息</a>
                    </dd>
                    <dd>
                        <a href="{% url 'xadmin:login' %}">退出登录</a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index">
                <a href="{% url 'xadmin:student' student.id %}">首页</a>
            </li>
        </ul>
    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
    <!-- 右侧主体开始 -->
    <div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space5">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-body ">
                            <blockquote class="layui-elem-quote">
                                你的学习质量评级为:{{student.level}}
                            </blockquote>
	                        <table class="layui-hide" id="test" lay-filter="test"></table>   
                            <blockquote class="layui-elem-quote">
                                建议：{{student.advice}}
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	
	    <script>
	    layui.use(['table','jquery'], function(){
	      //jquery取值
	      var sid = $("#sid").val();
        
	      var table = layui.table;  
	      var $$=layui.jquery;
	      table.render({
	        elem: '#test'
	        ,url:'/studentapi/' + sid
	        ,title: '用户数据表'
	        ,cols: [[
	          {field:'id', title:'学号',  fixed: 'left', unresize: true, sort: true}
	          ,{field:'name', title:'姓名'}
	          ,{field:'video_watching_counts', title:'视频观看个数'}
	          ,{field:'video_watching_seconds', title:'视频观看时长'}
	          ,{field:'course_discuss_related', title:'相关评论数'}
	          ,{field:'course_discuss_unrelated', title:'无关评论数'}
	          ,{field:'discuss_topic_numbers', title:'评论区主题数'}
	          ,{field:'discussion_comment_and_reply_numbers', title:'讨论区评论和回复数'}
	          ,{field:'spoc_score', title:'慕课成绩'}
	          ,{field:'test_mean', title:'单元测试平均成绩'}
	          ,{field:'level', title:'学习质量等级'}
	        ]]
	      });
	    });	//layui.use结束
	    </script>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
</body>
</html>

xadmin/templates/xadmin/teachclass.html
<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title>学生学习质量监测系统</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
	<link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/layui/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
</head>
<body class="index">
    <!-- 以下隐藏input是为了实现jsp全局变量引入到js中便于layui url传值 -->
	<input type="hidden" id="tid" value="{{teacher.id}}">
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo">
            <a href="{% url 'xadmin:teachclass' teacher.id %}">学生学习质量监测系统 </a>
        </div>
        <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    {{teacher.info}}
                </a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd>
                        <a onclick="x_admin_show('个人信息','http://www.baidu.com')">个人信息</a>
                    </dd>
                    <dd>
                        <a onclick="xadmin.open('弹出指定宽高','/login',600,400)">
                            监测模型设置</a></dd>
                    </dd>
                    <dd>
                        <a href="{% url 'xadmin:login' %}">退出登录</a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index">
                <a href="{% url 'xadmin:teachclass' teacher.id %}">首页</a>
            </li>
        </ul>
    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
    <!-- 右侧主体开始 -->
    <div>
	    <div class="x-nav">
            <span class="layui-breadcrumb">
                <a><cite>所授班级</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
            <i class="layui-icon" style="line-height:30px">ဂ</i></a>
        </div>

	    <table class="layui-hide" id="test" lay-filter="test"></table>   
	
	    <script type="text/html" id="barDemo">
     		<a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="table">表格</a>
     		<a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="chart">图表</a>
	    </script>           
	 
	    <script>
	    layui.use(['table','jquery'], function(){
	      //jquery取值
	      var tid = $("#tid").val();
        
	      var table = layui.table;  
	      var $$=layui.jquery;
	      table.render({
	        elem: '#test'
	        ,url:'/teachclassapi/' + tid
	        ,title: '用户数据表'
	        ,cols: [[
	          {field:'id', title:'班级编号',  fixed: 'left', unresize: true, sort: true}
	          ,{field:'name', title:'班级名称'}
	          ,{fixed: 'right', title:'操作', toolbar: '#barDemo'}
	        ]]
	        ,page: true
	      });
      
	      //监听行工具事件
	      table.on('tool(test)', function(obj){
	    	var data=obj.data
            if (obj.event === 'table') {
	            var urlval='/teachclass/' + tid + '/class/' + data.id + '/table/'
            }
            else {
	            var urlval='/teachclass/' + tid + '/class/' + data.id + '/chart/'
            }
    		$$.get(urlval,{},
    			function(data,status){
    				window.location.href = urlval;
    		});
	      });	//table.on结束
	    });	//layui.use结束
	    </script>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
</body>
</html>

xadmin/templates/xadmin/teachstudentchart.html
<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title>学生学习质量监测系统</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
	  <link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/layui/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
</head>
<body class="index">
    <!-- 以下隐藏input是为了实现jsp全局变量引入到js中便于layui url传值 -->
	<input type="hidden" id="cid" value="{{class.id}}">
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo">
            <a href="{% url 'xadmin:teachclass' teacher.id %}">学生学习质量监测系统 </a>
        </div>
        <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    {{teacher.info}}
                </a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd>
                        <a onclick="x_admin_show('个人信息','http://www.baidu.com')">个人信息</a>
                    </dd>
                    <dd>
                        <a href="{% url 'xadmin:login' %}">退出登录</a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index">
                <a href="{% url 'xadmin:teachclass' teacher.id %}">首页</a>
            </li>
        </ul>
    </div>
    <!-- 顶部结束 -->
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
    <!-- 右侧主体开始 -->
    <div>
	    <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="{% url 'xadmin:teachclass' teacher.id %}" >所授班级</a>
                <a><cite>{{class.name}}</cite></a>
            </span>
        </div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space5">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-body ">
                            <div id="main" style="width: 100%;height:400px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
	          var cid = $("#cid").val();
            $.get('/studentsapi/' + cid).done(function(data) {
              console.log(data.statistics)
              var chartDom = document.getElementById('main');
              var myChart = echarts.init(chartDom);
              myChart.setOption({
                title: {
                  text: '学习质量饼状图',
                  subtext: '不合格(<70)/良好(70-85)/优秀(>85)',
                  left: 'center'
                },
                tooltip: {
                  trigger: 'item',
                  formatter: "{d}%",
                },
                legend: {
                  orient: 'vertical',
                  left: 'left'
                },
                series: [
                  {
                    name: '学习质量等级',
                    type: 'pie',
                    radius: '50%',
                    data: data.statistics,
                    // data: [
                    //   { value: 1048, name: 'Search Engine' },
                    //   { value: 735, name: 'Direct' },
                    //   { value: 580, name: 'Email' },
                    //   { value: 484, name: 'Union Ads' },
                    //   { value: 300, name: 'Video Ads' }
                    // ],
                    emphasis: {
                      itemStyle: {
                        shadowBlur: 10,
                        shadowOffsetX: 0,
                        shadowColor: 'rgba(0, 0, 0, 0.5)'
                      }
                    }
                  }
                ]
              });
            })
        </script>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
</body>
</html>

xadmin/templates/xadmin/teachstudenttable.html
<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title>学生学习质量监测系统</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
	<link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/layui/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
</head>
<body class="index">
    <!-- 以下隐藏input是为了实现jsp全局变量引入到js中便于layui url传值 -->
	<input type="hidden" id="cid" value="{{class.id}}">
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo">
            <a href="{% url 'xadmin:teachclass' teacher.id %}">学生学习质量监测系统 </a>
        </div>
        <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    {{teacher.info}}
                </a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd>
                        <a onclick="x_admin_show('个人信息','http://www.baidu.com')">个人信息</a>
                    </dd>
                    <dd>
                        <a href="{% url 'xadmin:login' %}">退出登录</a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index">
                <a href="{% url 'xadmin:teachclass' teacher.id %}">首页</a>
            </li>
        </ul>
    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
    <!-- 右侧主体开始 -->
    <div>
	    <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="{% url 'xadmin:teachclass' teacher.id %}" >所授班级</a>
                <a><cite>{{class.name}}</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
            <i class="layui-icon" style="line-height:30px">ဂ</i></a>
        </div>
	    <table class="layui-hide" id="test" lay-filter="test"></table>   
	
	    <script>
	    layui.use(['table','jquery'], function(){
	      //jquery取值
	      var cid = $("#cid").val();
        
	      var table = layui.table;  
	      var $$=layui.jquery;
	      table.render({
	        elem: '#test'
	        ,url:'/studentsapi/' + cid
	        ,title: '用户数据表'
	        ,cols: [[
	          {field:'id', title:'学号',  fixed: 'left', unresize: true, sort: true}
	          ,{field:'name', title:'姓名'}
	          ,{field:'video_watching_counts', title:'视频观看个数'}
	          ,{field:'video_watching_seconds', title:'视频观看时长'}
	          ,{field:'course_discuss_related', title:'相关评论数'}
	          ,{field:'course_discuss_unrelated', title:'无关评论数'}
	          ,{field:'discuss_topic_numbers', title:'评论区主题数'}
	          ,{field:'discussion_comment_and_reply_numbers', title:'讨论区评论和回复数'}
	          ,{field:'spoc_score', title:'慕课成绩'}
	          ,{field:'test_mean', title:'单元测试平均成绩'}
	          ,{field:'level', title:'学习质量等级'}
	        ]]
	        ,page: true
	      });
	    });	//layui.use结束
	    </script>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
</body>
</html>